import 'fake-indexeddb/auto';
import Dexie from 'dexie';
import { afterEach,describe,expect,it } from 'vitest';
import { TindahanDB } from '@/db/database';
import { SettingsService,type BackupFile } from './settings.service';
describe('validated backup and recovery',()=>{let database:TindahanDB|undefined;afterEach(async()=>{if(database){const name=database.name;database.close();await Dexie.delete(name);database=undefined;}});async function setup(){database=new TindahanDB(`backup-${crypto.randomUUID()}`);await database.open();return new SettingsService(database)}
 it('exports complete metadata, counts, and a verifiable checksum',async()=>{const service=await setup();await database!.categories.put({id:'cat-1',name:'Drinks'});const backup=await service.exportData();expect(backup).toMatchObject({kind:'tindahan-backup',schemaVersion:7,deviceId:expect.any(String),exportedAt:expect.any(String),checksum:expect.stringMatching(/^[a-f0-9]{64}$/)});expect(backup.recordCounts.categories).toBe(1);expect((await service.validateBackup(backup)).totalRecords).toBeGreaterThanOrEqual(1)});
 it('rejects damaged content before active records change',async()=>{const service=await setup();await database!.categories.put({id:'cat-1',name:'Original'});const backup=await service.exportData();const damaged=structuredClone(backup) as BackupFile;(damaged.data.categories[0] as Record<string,unknown>).name='Tampered';await expect(service.importData(damaged)).rejects.toThrow('checksum');expect((await database!.categories.get('cat-1'))?.name).toBe('Original')});
 it('restores all tables transactionally, rehydrates dates, and retains a pre-restore recovery point',async()=>{const service=await setup();await database!.categories.put({id:'cat-1',name:'Backup category'});await database!.stockMovements.put({id:'move-1',productId:'product-1',batchId:'batch-1',date:new Date('2026-01-02T03:04:05Z'),type:'adjustment',quantity:1,notes:''});const backup=await service.exportData();await database!.categories.clear();await database!.categories.put({id:'other',name:'Replace me'});await service.importData(JSON.parse(JSON.stringify(backup)));expect(await database!.categories.get('other')).toBeUndefined();expect((await database!.categories.get('cat-1'))?.name).toBe('Backup category');expect((await database!.stockMovements.get('move-1'))?.date).toBeInstanceOf(Date);expect(await database!.migrationBackups.count()).toBe((backup.recordCounts.migrationBackups??0)+1);expect((await database!.auditLogs.toArray()).at(-1)).toMatchObject({action:'backup:restore',entityType:'backup'})});
 it('rejects incomplete table sets',async()=>{const service=await setup();const backup=await service.exportData();delete backup.data.products;await expect(service.validateBackup(backup)).rejects.toThrow('missing')});
});