import 'fake-indexeddb/auto';
import {beforeEach,describe,expect,it}from'vitest';
import {db}from'@/db/database';
import {InventoryLedgerService}from'./inventoryLedger.service';
import {inventoryRepo}from'./inventory.repository';
describe('inventory ledger',()=>{
 const service=new InventoryLedgerService(db);
 beforeEach(async()=>{await db.transaction('rw',[db.inventoryBatches,db.stockMovements,db.auditLogs,db.syncQueue,db.storeSettings],async()=>{await Promise.all([db.inventoryBatches.clear(),db.stockMovements.clear(),db.auditLogs.clear(),db.syncQueue.clear(),db.storeSettings.clear()]);await db.storeSettings.put({id:'store-1',name:'Store',ownerName:'',address:'',contact:'',currency:'PHP',timezone:'Asia/Manila',expirationWarningDays:30,allowNegativeInventory:false,themePreference:'light'});await db.inventoryBatches.put({id:'b1',productId:'p1',quantityReceived:10,remainingQuantity:10,unitCost:1,restockDate:new Date(),referenceNumber:'',notes:''});await db.stockMovements.put({id:'m0',productId:'p1',batchId:'b1',type:'restock',quantity:10,date:new Date(),notes:''});});});
 it('records an immutable movement, cache update, audit, and queue atomically',async()=>{const id=await service.record({productId:'p1',batchId:'b1',type:'damaged',quantity:-2,notes:'Broken'});expect((await db.inventoryBatches.get('b1'))?.remainingQuantity).toBe(8);expect(await db.stockMovements.get(id)).toMatchObject({quantity:-2,type:'damaged'});expect(await db.syncQueue.toCollection().first()).toMatchObject({entityType:'inventory_movement',entityId:id,operation:'transaction'});});
 it('blocks local negative stock when disabled and reports cache discrepancies',async()=>{await expect(service.record({productId:'p1',batchId:'b1',type:'sale',quantity:-11,notes:''})).rejects.toThrow('Insufficient');await db.inventoryBatches.update('b1',{remainingQuantity:9});expect(await service.reconcile()).toEqual([expect.objectContaining({batchId:'b1',cachedQuantity:9,movementQuantity:10,difference:-1})]);});
 it('queues a restock batch and its opening movement as one operation',async()=>{const batchId=await inventoryRepo.restockProduct({product:{id:'p2',name:'Rice',sku:'',barcode:'',categoryId:'c',unit:'bag',costPrice:1,sellingPrice:2,reorderLevel:0,description:'',active:true},quantityReceived:20,unitCost:1});expect(await db.inventoryBatches.get(batchId)).toMatchObject({remainingQuantity:20});expect(await db.syncQueue.toCollection().first()).toMatchObject({entityType:'inventory_restock',entityId:batchId,payload:{batch:{id:batchId},movement:{quantity:20,type:'restock'}}});});
});